#!/bin/bash

SRCDIR=Ayaorihime/Domain
TGTDIR=kw-uni

SRCFILE=$SRCDIR/DecoderKeys.cs
TGTFILE=$TGTDIR/KeysAndChars/deckey_id_defs.h

cat <<EOS > $TGTFILE
// DO NOT EDIT THIS FILE!!!!
// このファイルは $0 により $SRCFILE から自動的に作成されました ($(date '+%Y/%m/%d %H:%M:%S'))
#pragma once

EOS

sed -n '/public static partial class DecoderKeys/,/END_OF_AUTO_MAKE/ p' $SRCFILE | \
    tail -n +2 | \
    grep -v '^ *[{}]' | \
    grep -v 'private' | \
    sed 's/^ *//' | \
    sed 's/public const int/#define/' | \
    sed 's/= /(/' | \
    sed 's/;.*/)/' >> $TGTFILE

cat <<EOS >> $TGTFILE

namespace deckey_id_defs { const wchar_t* GetDeckeyNameFromId(int id); }
#define DECKEY_NAME_FROM_ID(id) deckey_id_defs::GetDeckeyNameFromId(id)
EOS

echo "$TGTFILE created"

###
TGTFILE1=$TGTDIR/KeysAndChars/deckey_id_defs.cpp

cat <<EOS > $TGTFILE1
// DO NOT EDIT THIS FILE!!!!
// このファイルは $0 により $SRCFILE から自動的に作成されました ($(date '+%Y/%m/%d %H:%M:%S'))

#include "string_type.h"
#include "deckey_id_defs.h"

namespace deckey_id_defs {

    std::map<int, const wchar_t*> deckeyId_name_map = {
EOS

sed -n -r 's/^ *public const int *(\w+)_DECKEY *= *([^;]+).*$/        {(\2), _T("\1")},/p' $SRCFILE >> $TGTFILE1

cat <<EOS >> $TGTFILE1
    };

    const wchar_t* GetDeckeyNameFromId(int id) {
        auto iter = deckeyId_name_map.find(id);
        return iter != deckeyId_name_map.end() ? iter->second : _T("?");
    }

} // namespace deckey_id_defs
EOS

echo "$TGTFILE1 created"

###
TGTFILE2=$SRCDIR/DecoderKeysMap.cs

cat <<EOS > $TGTFILE2
// DO NOT EDIT THIS FILE!!!!
// このファイルは $0 により $SRCFILE から自動的に作成されました ($(date '+%Y/%m/%d %H:%M:%S'))

using System;

using System.Collections.Generic;
using System.Linq;
using System.Text;

using Utils;

namespace KanchokuWS
{
    public static partial class DecoderKeys
    {
        private static Dictionary<int, string> KeyMap = new Dictionary<int, string>{
EOS

sed -n -r 's/^ *public const int *(\w+)_DECKEY *= *([^;]+).*$/            { \2, "\1" },/p' $SRCFILE >> $TGTFILE2

cat <<EOS >> $TGTFILE2
        };

        public static string GetDeckeyNameFromId(int id) {
            return KeyMap._safeGet(id) ?? "?";
        }
    }

} // namespace deckey_id_defs
EOS

echo "$TGTFILE2 created"
